//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constellation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public int idMain { get; set; }
        public Nullable<int> Food { get; set; }
        public string MainImagePath { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> NTable { get; set; }
        public Nullable<int> CountPerson { get; set; }
        public Nullable<int> Worker { get; set; }
    
        public virtual Foods Foods { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
